# syntax=docker/dockerfile:1.7

FROM nginx:1.28-alpine

COPY Client/nginx.conf /etc/nginx/nginx.conf
COPY Client/build/web /usr/share/nginx/html

USER nginx
EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
